# DeepL API key
# *You can get it here: https://www.deepl.com/pro?utm_source=github&utm_medium=github-java-readme#developer
# As of 23.02.2024 You can translate 500 000 characters per month for FREE

auth_key:
